app/app/models/post.py
from sqlalchemy.sql import func

from . import db

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime(timezone=True),
                          server_default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

    def save(self):
        db.session.add(self)
        db.session.commit()

app/app/models/posts.py
from flask_sqlalchemy import SQLAlchemy

from . import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime(timezone=True),
                           server_default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

app/app/forms/edit_profile.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Length

from ..models.user import User

class EditProfile(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=500)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfile, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

app/app/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired

class Login(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

app/app/forms/post.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length

class Post(FlaskForm):
    post = TextAreaField('Say something', validators=[
        DataRequired(), Length(min=1, max=140)])
    submit = SubmitField('Submit')

app/app/forms/register.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo

from ..models.user import User

class Register(FlaskForm):
    firstname = StringField('First Name', validators=[DataRequired()])
    lastname = StringField('Last Name', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

app/app/views/home.py
from flask import render_template, redirect, Blueprint, url_for, flash, request
from flask_login import login_required, current_user

from flask import current_app as app

from ..models import db
from ..models.post import Post as PostModel
from ..forms.post import Post as PostForm

home_blueprint = Blueprint('home', __name__)

@home_blueprint.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    form = PostForm()
    if form.validate_on_submit():
        post = PostModel(body=form.post.data, author=current_user)
        post.save()
        flash('Your post is now live!')
        return redirect(url_for('.home'))
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page, app.config['POSTS_PER_PAGE'], False)

    next_url = url_for('.home', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('.home', page=posts.prev_num) \
        if posts.has_prev else None

    return render_template("home.html", title='Home Page', form=form,
                           posts=posts.items, next_url=next_url,
                           prev_url=prev_url)

app/app/views/joystream.py
from flask import render_template, Blueprint, request, url_for
from flask_login import login_required

from flask import current_app as app

from ..models.post import Post

joystream_blueprint = Blueprint('joystream', __name__)

@joystream_blueprint.route('/joystream')
@login_required
def joystream():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, app.config['POSTS_PER_PAGE'], False)

    next_url = url_for('.joystream', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('.joystream', page=posts.prev_num) \
        if posts.has_prev else None

    return render_template('joystream.html',
                           title='The Joystream',
                           posts=posts.items,
                           next_url=next_url,
                           prev_url=prev_url)

app/app/views/login.py
from flask import render_template, redirect, make_response, Blueprint, url_for, flash
from flask_login import current_user, login_user

from ..models.user import User
from ..forms.login import Login

login_blueprint = Blueprint('login', __name__)

@login_blueprint.route('/hello')
def hello():
    return make_response('hello world', 200)

@login_blueprint.route('/', methods=['GET', 'POST'])
@login_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    login_form = Login()
    if login_form.validate_on_submit():
        # debug
        print('Login requested for user {}, remember_me={}'.format(
            login_form.username.data, login_form.remember_me.data))

        user = User.query.filter_by(username=login_form.username.data).first()
        if user is None or not user.verify_password(login_form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('.login'))
        login_user(user, remember=login_form.remember_me.data)
        return redirect(url_for('profile.profile'))
    return render_template('login.html', title='Sign In', form=login_form)

app/app/views/profile.py
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask_login import current_user, login_required

from flask import current_app as app

from ..models.user import User
from ..models.post import Post
from ..models import db
from ..forms.edit_profile import EditProfile

profile_blueprint = Blueprint('profile', __name__)

@profile_blueprint.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, app.config['POSTS_PER_PAGE'], False)

    next_url = url_for('.profile', username=user.username, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('.profile', username=user.username, page=posts.prev_num) \
        if posts.has_prev else None

    return render_template('profile.html', user=user, posts=posts.items,
                           next_url=next_url, prev_url=prev_url)


@profile_blueprint.route('/profile/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfile(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        current_user.save()
        flash('Your changes have been saved.')
        return redirect(url_for('.profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title='Edit Profile',
                           form=form)


@profile_blueprint.route('/profile/<username>/follow')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None or user == current_user:
        flash('There was a problem following {}.'.format(username))
        return redirect(url_for('.profile', username=current_user.username))
    current_user.follow(user)
    db.session.commit()
    flash('You are following {}!'.format(username))
    return redirect(url_for('.profile', username=username))


@profile_blueprint.route('/profile/<username>/unfollow')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None or user == current_user:
        flash('There was a problem unfollowing {}.'.format(username))
        return redirect(url_for('.profile', username=current_user.username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are no longer following {}.'.format(username))
    return redirect(url_for('.profile', username=username))

app/app/views/register.py
from flask import render_template, redirect, Blueprint, url_for, flash
from flask_login import current_user

from ..models.user import User
from ..forms.register import Register

blueprint_register = Blueprint('register', __name__)

@blueprint_register.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    register_form = Register()
    if register_form.validate_on_submit():
        user = User(username=register_form.username.data,
                    email=register_form.email.data,
                    firstname=register_form.firstname.data,
                    lastname=register_form.lastname.data)
        user.hash_password(register_form.password.data)
        user.save()
        flash('Welcome to the Joystream!')
        return redirect(url_for('session.login'))
    return render_template('register.html', title='Register', form=register_form)

app/app/views/session.py
from datetime import datetime
from flask import render_template, redirect, Blueprint, url_for, flash
from flask_login import current_user, login_user, logout_user

from ..models.user import User
from ..forms.login import Login

session_blueprint = Blueprint('session', __name__)

@session_blueprint.route('/', methods=['GET', 'POST'])
@session_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home.home'))
    login_form = Login()
    if login_form.validate_on_submit():
        user = User.query.filter_by(username=login_form.username.data).first()
        if user is None or not user.verify_password(login_form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('.login'))
        login_user(user, remember=login_form.remember_me.data)
        return redirect(url_for('home.home'))
    return render_template('login.html', title='Sign In', form=login_form)


@session_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('.login'))


@session_blueprint.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        current_user.save()

app/app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
{% endblock %}

{% block head %}
    {{super()}}
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="{{url_for('static', filename='menu.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='notification.js')}}"></script>
{% endblock %}

{% block title %}
    {% if title %}{{ title }} - Joystream{% else %}Welcome to the Joystream{% endif %}
{% endblock %}

{% block body %}
<section id="main_body">
    <div class="container fill-viewport align-items-center">
        {% block navbar %}
            <nav class="navbar navbar-inverse menu">
              <div class="container-fluid">
                <div class="navbar-header">
                  <a class="navbar-brand">The Joystream</a>
                </div>
                <ul class="nav navbar-nav menu">
                  <li><a href="{{ url_for('home.home') }}">Home</a></li>
                  {% if current_user.is_anonymous %}
                       <li><a href="{{ url_for('session.login') }}">Login</a></li>
                  {% else %}
                       <li><a href="{{ url_for('profile.profile', username=current_user.username) }}">Profile</a></li>
                       <li><a href="{{ url_for('joystream.joystream') }}">The Joystream</a></li>
                       <li><a href="{{ url_for('session.logout') }}">Logout</a></li>
                  {% endif %}
                </ul>
              </div>
            </nav>
        {% endblock %}
        {% block content %}
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="message">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
                {# sub-template is inserted here: #}
                {% block app_content %}
                {% endblock %}
        {% endblock %}
    </div>
</section>
{% endblock %}

app/app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <h1>Edit Profile</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/app/templates/home.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Hi, {{ current_user.username }}!</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-12">
        {% if posts %}
            {% for post in posts %}
                {% include 'post.html' %}
            {% endfor %}
            {% if prev_url %}
                <a href="{{ prev_url }}">Newer posts</a>
            {% endif %}
            {% if next_url %}
                <a href="{{ next_url }}">Older posts</a>
            {% endif %}
        {% else %}
            <p>Pretty empty here. Why dont you have a look <a href="{{ url_for('joystream.joystream') }}">around</a></p>
        {% endif %}
        </div>
    </div>
{% endblock %}

app/app/templates/joystream.html
{% extends "base.html" %}

{% block content %}
    <h1>Hi, {{ current_user.username }}!</h1>
    {% for post in posts %}
        {% include 'post.html' %}
    {% endfor %}
    {% if prev_url %}
        <a href="{{ prev_url }}">Newer posts</a>
    {% endif %}
    {% if next_url %}
        <a href="{{ next_url }}">Older posts</a>
    {% endif %}
{% endblock %}

app/app/templates/login.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Sign In</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
            <p>New User? <a href="{{ url_for('register.register') }}">Click to Register!</a></p>
        </div>

    </div>
{% endblock %}

app/app/templates/post.html
<table class="table table-hover table-borderless table-white">
    <tr>
        <td width="70px">
            <a href="{{ url_for('profile.profile', username=post.author.username) }}">
                <img src="{{ post.author.avatar(70) }}" />
            </a>
        </td>
        <td>
            <a href="{{ url_for('profile.profile', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
            says:
            <br>
            {{ post.body }}
        </td>
    </tr>
</table>

app/app/templates/profile.html
{% extends "base.html" %}

{% block app_content %}
    <div class="row">
        <div class="col-md-2">
            <img src="{{ user.avatar(128) }}"></td>
        </div>
        <div class="col-md-10">
            <h2>{{ user.username }}</h2>
            <p>{{ user.firstname }} {{ user.lastname }}</p>
            {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
            {% if user.last_seen %}<p>Last seen on: {{ user.last_seen }}</p>{% endif %}
            <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
            {% if user == current_user %}
                <p><a href="{{ url_for('profile.edit_profile') }}">Edit your profile</a></p>
            {% elif not current_user.is_following(user) %}
                <p><a href="{{ url_for('profile.follow', username=user.username) }}">Follow</a></p>
            {% else %}
                <p><a href="{{ url_for('profile.unfollow', username=user.username) }}">Unfollow</a></p>
            {% endif %}
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-12">
            {% if posts %}
                <h3>Your posts:</h3>
                {% for post in posts %}
                    {% include 'post.html' %}
                {% endfor %}
            {% else %}
                <p>Pretty empty here. Why don't you <a href="{{ url_for('home.home') }}">post</a> something</p>
            {% endif %}
            {% if prev_url %}
                <a href="{{ prev_url }}">Newer posts</a>
            {% endif %}
            {% if next_url %}
                <a href="{{ next_url }}">Older posts</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/app/templates/register.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Register</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}